.TH lia 1 "23 Feb 2018" "version 1.0"
.SH NAME
lia \- LDAP Inventory for Ansible
.SH SYNOPSIS
.B lia
.RB [ \-h ]
.RB ( \-\-list | \-\-host
.IR HOST )
.SH DESCRIPTION
.B lia
is a helper script to query hosts, groups, and variables from your LDAP
server, and provide it to \fBansible\fR(1).
.B lia
is highly configurable to support caching and adjust to any LDAP schema.

The program will cache the inventory in JSON format, and serve it until the
cache expires.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show usage information, and exit.
.TP
.B \-\-list
Print all groups and variables.
.TP
.BI \-\-host\  HOST
Print variables for the host \fIHOST\fR.
.SH "EXIT STATUS"
Returns zero if the inventory was retrieved.
.SH ENVIRONMENT
.TP
.B LOG_LEVEL
Sets verbosity of logging sent to standard error.
Recognized level are:
.BR CRITICAL ,
.BR ERROR ,
.BR WARNING " (default),"
.BR INFO ", and "
.BR DEBUG .
.SH FILES
.TP
.IR $XDG_CONFIG_HOME/lia.json ", " ~/.config/lia.json
Configuration file, see \fBlia.json\fR(5).
.TP
.IR $XDG_CACHE_HOME/lia.json ", " ~/.cache/lia.json
Cached inventory.
.SH "CONFORMING TO"
.IP \(em 4
.UR http://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html
Developing Dynamic Inventory Sources
.UE
.IP \(em 4
.UR https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html
XDG Base Directory Specification
.UE
.SH "SEE ALSO"
.BR lia.json (5),
.BR ansible (1)
